<?php

/**
 * @file
 * A module that updates object records with data hub image data on cron.
 */

/**
 * Implements hook_cron() function.
 */
function aic_update_object_cron() {
  module_load_include('inc', 'aicapp', 'includes/aicapp.admin');
  // Update object image data.
  aicapp_update_object_image_data();
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 */
function aic_update_object_help($path, $arg) {
  switch ($path) {
    case "admin/help#aic_update_object":
      return t("This module obtains image data from the Art Institute’s instance of Solr to update object records.<br /> This module was created after the implementation of custom cropping of images, when it became required to have image data in the CMS. <br />This module runs on the Drupal cron. <br />A database backup is recommended before turning this module on.<br /> If not additional updates are needed, we recommend disabling the module after the update.");
      break;
  }
}
