<?php

/**
 * Implements  hook_menu().
 */
function aicapp_migrate_menu() {
  $items['admin/config/system/aic/migrations'] = array(
    'title' => 'Content Migration',
    'description' => 'Tools to migrate content types and from v1 format to v2 format.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('aicapp_migrate_admin_migrate'),
    'access callback' => 'user_access',
    'access arguments' => array('administer aic api settings'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_query_TAG_alter().This is used for data migration queries.
 */
function aicapp_migrate_query_no_commentary_items_alter(QueryAlterableInterface $query) {
  $query->leftJoin('field_data_field_audio_commentary', 'o', 'node.nid = o.entity_id');
  $query->isNull('o.field_audio_commentary_value');
}

/**
 * Implements hook_query_TAG_alter(). This is used for data migration queries.
 */
function aicapp_migrate_query_no_tour_stops_items_alter(QueryAlterableInterface $query) {
  $query->leftJoin('field_data_field_tour_stops', 'o', 'node.nid = o.entity_id');
  $query->isNull('o.field_tour_stops_value');
}

/**
 * Form callback.
 */
function aicapp_migrate_admin_migrate() {
  $form = array();
  $all_migrations_complete = variable_get('aicapp_migrate_v1_v2', FALSE);
  // Data migration between v1 and v2.
  if (variable_get('aicapp_migrate_v1_v2_language', FALSE) && variable_get('aicapp_migrate_v1_v2_fields', FALSE)) {
    $all_migrations_complete = TRUE;
    $overview = t('All migrations complete');
  }
  global $language;
  $form['aicapp_data'] = array(
    '#type' => 'fieldset',
    '#collapsible' => $all_migrations_complete,
    '#collapsed' => $all_migrations_complete,
    '#title' => t('Content language and field migration'),
    '#tree' => TRUE,
  );
  if ($all_migrations_complete) {
    $form['aicapp_data']['migration_repeat'] = array(
      '#prefix' => t('All data has been migrated.'),
      '#type' => 'submit',
      '#value' => t('Repeat Migration'),
    );
  }
  else {
    $counts = $types = array(
      AICAPP_TYPE_AUDIO => t('Audio'),
      AICAPP_TYPE_TOUR => t('Tours'),
    );
    // Set default audio and tour counts.
    $counts[AICAPP_TYPE_TOUR] = 0;
    $counts[AICAPP_TYPE_AUDIO] = 0;
    $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', $types, 'IN')
      ->propertyCondition('language', LANGUAGE_NONE, '=');
    $result = $query->execute();
    $form['aicapp_data']['migration_language_prefix']['#markup'] = '<p><strong>' . t('Content Language Migration') . '</strong></p>';

    if (empty($result['node'])) {
      variable_set('aicapp_migrate_v1_v2_language', TRUE);
      $form['aicapp_data']['migration_language_complete'] = array(
        '#markup' => t('All content items have been updated to %lang.', array('%lang' => strtoupper($language->language))),
      );
    }
    else {
      $form['aicapp_data']['migration_language_types'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Select content type(s) to update to @lang:', array('@lang' => $language->language)),
        '#options' => $types,
        '#default_value' => array(),
        '#description' => t('Every node of the chosen type(s) will be updated to English.'),
      );
      $form['aicapp_data']['migration_language_submit'] = array(
        '#type' => 'submit',
        '#value' => t('Update Content Language'),
      );
    }
    $form['aicapp_data']['migration_fields_prefix']['#markup'] = '<p><strong>' . t('Content Fields Migration') . '</strong></p>';
    $types = array(
      AICAPP_TYPE_OBJECT => t('Objects'),
      AICAPP_TYPE_TOUR => t('Tours'),
    );
    // Set object and reset tour counts;
    $counts[AICAPP_TYPE_OBJECT] = 0;
    $counts[AICAPP_TYPE_TOUR] = 0;
    foreach ($types as $type) {
      $query = new EntityFieldQuery();
      $query
        ->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', $type, '=');
      if ($type === AICAPP_TYPE_OBJECT) {
        $query->addTag('no_commentary_items');
      }
      elseif ($type === AICAPP_TYPE_TOUR) {
        $query->addTag('no_tour_stop');
      }
      $result = $query->execute();
      if (!empty($result['node'])) {
        $counts[$type] = count($result['node']);
      }
    }
    if ($counts[AICAPP_TYPE_OBJECT] && $counts[AICAPP_TYPE_TOUR]) {
      variable_set('aicapp_migrate_v1_v2_fields', TRUE);
      $form['aicapp_data']['migration_fields_complete'] = array(
        '#markup' => '<p>' . t('All content items fields have been updated.') . '</p>',
      );
    }
    else {
      $form['aicapp_data']['migration_fields_types'] = array(
        '#type' => 'checkboxes',
        '#title' => t('Select content type(s) with fields to updated:'),
        '#options' => $types,
        '#default_value' => array(),
        '#description' => t('Every node of the chosen type(s) fields will be updated.'),
      );
      $form['aicapp_data']['migration_fields_submit'] = array(
        '#type' => 'submit',
        '#value' => t('Update Content Fields'),
      );
    }
  }
  return $form;
}

/**
 * Admin setting validation callback.
 */
function aicapp_migrate_admin_migrate_validate($form, &$form_state) {
  if ($form_state['clicked_button']['#value'] === 'Repeat Migration') {
    variable_set('aicapp_migrate_v1_v2', FALSE);
    variable_set('aicapp_migrate_v1_v2_language', FALSE);
    variable_set('aicapp_migrate_v1_v2_fields', FALSE);
    return;
  }
  if ($form_state['clicked_button']['#value'] === 'Update Content Language') {
    global $language;
    // What node type(s) are to be updated.
    $types = $form_state['values']['aicapp_data']['migration_language_types'];
    $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', $types, 'IN')
      ->propertyCondition('language', LANGUAGE_NONE, '=');
    $result = $query->execute();
    if (empty($result['node']) || empty($types)) {
      drupal_set_message('There were no items to migrate');
      variable_set('aicapp_migrate_v1_v2_language', TRUE);
      return;
    }
    foreach ($types as $type) {
      if (empty($type)) {
        continue;
      }
      foreach ($result['node'] as $nid => $obj) {
        $node = node_load($nid);
        $node->language = $language->language;
        node_save($node);
      }
      $message = t('All @type content items with no language have been set to English', array('@type' => $type));
      drupal_set_message($message);
    }
  }
  if ($form_state['clicked_button']['#value'] === 'Update Content Fields') {
    $counts = $to_add = array();
    $types = $form_state['values']['aicapp_data']['migration_fields_types'];
    foreach ($types as $type) {
      if (empty($type)) {
        continue;
      }
      $query = new EntityFieldQuery();
      $query
        ->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', $type, '=');
      if ($type === AICAPP_TYPE_OBJECT) {
        // Load all objects that have 0 audio commentary items.
        $query->addTag('no_commentary_items');
        // Five at a time for testing.
        $query->range(0, 100);
      }
      elseif (AICAPP_TYPE_TOUR) {
        // Load all tours.
        $query->addTag('no_tour_stop');
      }
      $result = $query->execute();
      $counts[$type] = !empty($result['node']) ? count($result['node']) : 0;
      if ($counts[$type]) {
        $i = 0;
        foreach ($result['node'] as $nid => $obj) {
          if (empty($obj->type) || $obj->type !== $type) {
            continue;
          }
          $i++;
          $changed = FALSE;
          $to_add = array();
          $node = node_load($nid);
          $callback = 'aicapp_migrate_migrate_type_' . $type;
          call_user_func_array($callback, array(&$node, &$changed, &$counts, &$i));


          if ($changed === TRUE) {
            node_save($node);
          }
        }
        $type_message = array('@type' => $type);
        drupal_set_message(t('All @type nodes have been migrated to use the new field format.', $type_message));
      }
    }
  }
}

/**
 * Helper function to migrate tour fields.
 */
function aicapp_migrate_migrate_type_tour(&$node, &$changed = FALSE, &$counts = array()) {
  $found = array(
    'field_t_object' => NULL,
    'field_t_audio' => NULL,
    'field_t_audio_bumper' => NULL,
  );

  // Check for field_object_selector_numbers, field_object_selector_number, and field_object_audio
  if (!empty($node->field_stops2[LANGUAGE_NONE])) {
    $ids = array();
    foreach ($node->field_stops2[LANGUAGE_NONE] as $key => $value) {
      $ids[] = $value['value'];
    }
    $stops = field_collection_item_load_multiple($ids);
    $stops = current($stops);
    foreach ($found as $field => $n) {
      if (!isset($stops->{$field}[LANGUAGE_NONE])) {
        continue;
      }
      foreach ($stops->{$field}[LANGUAGE_NONE] as $id => $stop) {
        $found[$field][] = $stop['nid'];
      }
    }
  }
  // In terms of selector numbers, there are 3 cases.
  $count_object = count($found['field_t_object']);
  $count_audio = count($found['field_t_audio']);
  $count_bumper = count($found['field_t_audio_bumper']);
  if ($count_object > $count_audio) {

  }
  elseif ($count_object < $count_audio) {

  }
  // Check if there are currently audio commentary items.
  if (!empty($node->field_tour_stops[LANGUAGE_NONE])) {
    foreach ($node->field_tour_stops[LANGUAGE_NONE] as $key => $value) {
      $field_collection_item_values[] = $value['value'];
    }
  }
  // Add the new audio commentary
  if (!empty($found['field_t_audio']) && empty($field_collection_item_values)) {
    foreach ($found['field_t_audio'] as $k => $audio_id) {
      // Setup the values in the structure expected by the field_collection entity.
      $item_values = array(
        'field_name' => 'field_tour_stops',
        'field_t_object' => array(
          LANGUAGE_NONE => array(array(
            'target_id' => $audio_id,
          ))
        )
      );
      if (isset($found['field_t_audio'][$k])) {
        $item_values['field_t_audio'] = array(
          LANGUAGE_NONE => array(array(
            'target_id' => $found['field_t_audio'][$k],
          ))
        );
      }
      if (isset($found['field_t_audio_bumper'][$k])) {
        $item_values['field_t_audio_bumper'] = array(
          LANGUAGE_NONE => array(array(
            'target_id' => $found['field_t_audio_bumper'][$k],
          ))
        );
      }
      $fc_item = entity_create('field_collection_item', $item_values);
      $fc_item->setHostEntity('node', $node);
      $fc_item->save();
    }
    $changed = TRUE;
  }
}

/**
 * Helper function to migrate object fields.
 */
function aicapp_migrate_migrate_type_object(&$node, &$changed = FALSE, &$counts = array(), &$i = 0) {
  $to_add = array();
  $found = array(
    'field_object_selector_numbers' => NULL,
    'field_object_selector_number' => NULL,
    'field_object_audio' => NULL,
  );
  // Check for field_object_selector_numbers, field_object_selector_number, and field_object_audio
  if (!empty($node->field_object_selector_numbers[LANGUAGE_NONE])) {
    $found['field_object_selector_numbers'] = $node->field_object_selector_numbers[LANGUAGE_NONE];
  }
  if (!empty($node->field_object_selector_number[LANGUAGE_NONE])) {
    $found['field_object_selector_number'] = $node->field_object_selector_number[LANGUAGE_NONE];
  }
  if (!empty($node->field_object_audio[LANGUAGE_NONE])) {
    // Uses 'nid' as value key instead of 'value'
    $found['field_object_audio'] = $node->field_object_audio[LANGUAGE_NONE];
  }
  $count_multi = count($found['field_object_selector_numbers']);
  $count_audio = count($found['field_object_audio']);
  // In terms of selector numbers, there are 3 cases.
  if ($count_multi === 1) {
    // One of each, make sure they are the same.
    if ($found['field_object_selector_number'] &&
      $found['field_object_selector_number'][0]['value'] === $found['field_object_selector_numbers'][0]['value']) {

      // Numbers match, there is 1 matching selector being used.
      $to_add[$i]['selector'][] = $found['field_object_selector_number'][0]['value'];
      if ($count_audio) {
        foreach ($found['field_object_audio'] as $k => $v) {
          $to_add[$i]['audio'][] = $found['field_object_audio'][$k]['nid'];
        }
      }
      else {
        // No audio found unset this selector to add.
        unset($to_add[$i]['selector']);
      }
    }
    else {
      // Number will take precendence.
      $to_add[$i]['selector'][] = $found['field_object_selector_number'][0]['value'];
      $to_add[$i]['selector'][] = $found['field_object_selector_numbers'][LANGUAGE_NONE][0]['value'];
      // Multi and single do not match. Check audio count.
      if ($count_audio > 1) {
        foreach ($found['field_object_audio'] as $k => $v) {
          $to_add[$i]['audio'][] = $found['field_object_audio'][$k]['nid'];
        }

      }
      elseif ($count_audio === 1) {
        $to_add[$i]['audio'][] = $found['field_object_audio'][0]['nid'];
        unset($to_add[$i]['selector'][1]);
      }
      else {
        // No audio found unset this selector to add.
        unset($to_add[$i]['selector']);
      }
    }
  }
  // More than one field_object_selector_numbers found.
  elseif ($count_multi > 1) {
    foreach ($found['field_object_selector_numbers'][LANGUAGE_NONE] as $k => $v) {
      $to_add[$i]['selector'][] = $found['field_object_selector_numbers'][$k]['value'];
    }
    if ($count_audio) {
      foreach ($found['field_object_audio'][LANGUAGE_NONE] as $k => $v) {
        $to_add[$i]['audio'][] = $found['field_object_audio'][$k]['nid'];
      }
    }
    else {
      unset($to_add[$i]['selector']);
    }
  }
  // No multiple count but found one selector
  elseif ($found['field_object_selector_number']) {
    $to_add[$i]['selector'][] = $found['field_object_selector_number'][0]['value'];
    if ($count_audio) {
      foreach ($found['field_object_audio'] as $k => $v) {
        $to_add[$i]['audio'][] = $found['field_object_audio'][$k]['nid'];
      }
    }
  }
  else {
  //  $i++;
  }
  return;
  // Check if there are currently audio commentary items.
  if (!empty($node->field_audio_commentary[LANGUAGE_NONE])) {
    foreach ($node->field_audio_commentary[LANGUAGE_NONE] as $key => $value) {
      $field_collection_item_values[] = $value['value'];
    }
  }
  // Add the new audio commentary
  if (!empty($to_add[$i]) && !empty($to_add[$i]['audio']) && empty($field_collection_item_values)) {
    foreach ($to_add[$i]['audio'] as $k => $audio_id) {
      // Setup the values in the structure expected by the field_collection entity.
      $item_values = array(
        'field_name' => 'field_audio_commentary',
        'field_audio_commentary_audio' => array(
          LANGUAGE_NONE => array(array(
            'target_id' => $audio_id
          )),
        ),
      );
      if (isset($to_add[$i]['selector'][$k])) {
        $item_values['field_object_selector_number'] = array(
          LANGUAGE_NONE => array(array(
            'value' => $to_add[$i]['selector'][$k]
          ))
        );
      }




      $fc_item = entity_create('field_collection_item', $item_values);
      $fc_item->setHostEntity('node', $node);
      $fc_item->save();
    }
    $changed = TRUE;
  }
}
