<?php
/**
 * @file
 * aic_mobile_cms_floor_map_export.features.node_export_features.inc
 */

/**
 * Implements hook_node_export_features_default().
 */
function aic_mobile_cms_floor_map_export_node_export_features_default() {
  $node_export = array(
  'code_string' => 'array(
  (object) array(
      \'changed\' => NULL,
      \'comment\' => \'0\',
      \'created\' => NULL,
      \'data\' => \'a:5:{s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}\',
      \'entity_translation_handler_id\' => \'node-map_floor-eid-2416-2426\',
      \'field_collection_deploy\' => array(
        \'field_floor_map\' => array(
          array(
            \'item_id\' => \'104\',
            \'revision_id\' => \'112\',
            \'field_name\' => \'field_floor_map\',
            \'default_revision\' => \'1\',
            \'archived\' => \'0\',
            \'uuid\' => \'94d96f51-81ea-46c8-97bd-1ee7803f2bb5\',
            \'field_floor_anchor_geolocation\' => array(
              \'und\' => array(
                array(
                  \'value\' => \'lat,long\',
                  \'format\' => NULL,
                  \'safe_value\' => \'lat,long\',
                ),
              ),
            ),
            \'field_floor_label\' => array(
              \'und\' => array(
                array(
                  \'value\' => \'0\',
                  \'format\' => NULL,
                  \'safe_value\' => \'0\',
                ),
              ),
            ),
            \'field_floor_map_anchor_pixel\' => array(
              \'und\' => array(
                array(
                  \'value\' => \'x,y\',
                  \'format\' => NULL,
                  \'safe_value\' => \'x,y\',
                ),
              ),
            ),
            \'field_floor_map_file\' => array(),
            \'field_floor_map_anchor_pixel_2\' => array(
              \'und\' => array(
                array(
                  \'value\' => \'x,y\',
                  \'format\' => NULL,
                  \'safe_value\' => \'x,y\',
                ),
              ),
            ),
            \'field_floor_anchor_geolocation_2\' => array(
              \'und\' => array(
                array(
                  \'value\' => \'lat,long\',
                  \'format\' => NULL,
                  \'safe_value\' => \'lat,long\',
                ),
              ),
            ),
            \'entity_view_prepared\' => TRUE,
          ),
          array(
            \'item_id\' => \'105\',
            \'revision_id\' => \'113\',
            \'field_name\' => \'field_floor_map\',
            \'default_revision\' => \'1\',
            \'archived\' => \'0\',
            \'uuid\' => \'6a7a7e41-f05f-4079-a86c-3f67796c0de0\',
            \'field_floor_anchor_geolocation\' => array(),
            \'field_floor_label\' => array(
              \'und\' => array(
                array(
                  \'value\' => \'1\',
                  \'format\' => NULL,
                  \'safe_value\' => \'1\',
                ),
              ),
            ),
            \'field_floor_map_anchor_pixel\' => array(),
            \'field_floor_map_file\' => array(),
            \'field_floor_map_anchor_pixel_2\' => array(),
            \'field_floor_anchor_geolocation_2\' => array(),
            \'entity_view_prepared\' => TRUE,
          ),
          array(
            \'item_id\' => \'106\',
            \'revision_id\' => \'114\',
            \'field_name\' => \'field_floor_map\',
            \'default_revision\' => \'1\',
            \'archived\' => \'0\',
            \'uuid\' => \'a4150ddd-aedb-4294-ac5b-6b5185fea590\',
            \'field_floor_anchor_geolocation\' => array(),
            \'field_floor_label\' => array(
              \'und\' => array(
                array(
                  \'value\' => \'2\',
                  \'format\' => NULL,
                  \'safe_value\' => \'2\',
                ),
              ),
            ),
            \'field_floor_map_anchor_pixel\' => array(),
            \'field_floor_map_file\' => array(),
            \'field_floor_map_anchor_pixel_2\' => array(),
            \'field_floor_anchor_geolocation_2\' => array(),
            \'entity_view_prepared\' => TRUE,
          ),
          array(
            \'item_id\' => \'107\',
            \'revision_id\' => \'115\',
            \'field_name\' => \'field_floor_map\',
            \'default_revision\' => \'1\',
            \'archived\' => \'0\',
            \'uuid\' => \'e56e896d-8874-4830-890a-d867aa8ba02f\',
            \'field_floor_anchor_geolocation\' => array(),
            \'field_floor_label\' => array(
              \'und\' => array(
                array(
                  \'value\' => \'3\',
                  \'format\' => NULL,
                  \'safe_value\' => \'3\',
                ),
              ),
            ),
            \'field_floor_map_anchor_pixel\' => array(),
            \'field_floor_map_file\' => array(),
            \'field_floor_map_anchor_pixel_2\' => array(),
            \'field_floor_anchor_geolocation_2\' => array(),
            \'entity_view_prepared\' => TRUE,
          ),
        ),
      ),
      \'field_floor_map\' => array(
        \'und\' => array(
          array(
            \'value\' => \'104\',
            \'revision_id\' => \'112\',
          ),
          array(
            \'value\' => \'105\',
            \'revision_id\' => \'113\',
          ),
          array(
            \'value\' => \'106\',
            \'revision_id\' => \'114\',
          ),
          array(
            \'value\' => \'107\',
            \'revision_id\' => \'115\',
          ),
        ),
      ),
      \'files\' => array(),
      \'language\' => \'en\',
      \'last_comment_timestamp\' => NULL,
      \'log\' => \'\',
      \'menu\' => NULL,
      \'name\' => \'Anonymous\',
      \'nid\' => NULL,
      \'node_export_drupal_version\' => \'7\',
      \'path\' => NULL,
      \'picture\' => \'0\',
      \'promote\' => \'1\',
      \'revision_timestamp\' => NULL,
      \'revision_uid\' => 1,
      \'status\' => \'1\',
      \'sticky\' => \'0\',
      \'title\' => \'Floor Maps\',
      \'tnid\' => \'0\',
      \'translate\' => \'0\',
      \'translations\' => (object) array(
          \'original\' => NULL,
          \'data\' => array(),
        ),
      \'type\' => \'map_floor\',
      \'uid\' => \'0\',
      \'uuid\' => \'1b0519f8-14ef-4144-a556-d2601df4331a\',
      \'vid\' => NULL,
      \'vuuid\' => \'9f494e11-caf0-4741-b867-698a71cc65ce\',
    ),
)',
);
  return $node_export;
}
